### ISSUE TITLE
encodage

### ISSUE THREAD

**Issue by biloucat** [D-BookeR/GUI_en_Python_avec_PyQt_5#1]
le fichier  0417_codes-sources-v1.0/qt-graphicsview/1-premiere-app/2-vues-multiples/test_scene.py
n'est pas en utf-8

**Comment by piedenis** [comment]
OK. Corrigé aussi pour 0417_codes-sources-v1.0/qt-graphicsview/1-premiere-app/2-vue-unique/test_scene.py
